version: '3'

services:
  mariadb:
    image: mariadb:10.3
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Zxczxc888
      MYSQL_USER: u839560_office
      MYSQL_PASSWORD: Zxczxc888

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links: 
      - mariadb:db
    ports:
      - 8765:80
    environment:
      MYSQL_ROOT_PASSWORD: Zxczxc888
    depends_on:
      - mariadb

  vue-build:
    build: ./public/view
    volumes:
      - ./hosts:/etc/nginx/conf.d
      - ./configs:/etc/nginx/sites-available
      - ./www:/dev/www
      - ./logs:/dev/log/nginx
    ports:
      - 80:80